# https://taskfile.dev

version: "3"

vars:
  PYTHON: python3

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  # Development tasks
  install:
    desc: Install development dependencies
    cmds:
      - uv sync --all-extras

  test:
    desc: Run tests
    cmds:
      - uv run pytest
      - go test ./...

  test-coverage:
    desc: Run tests with coverage report
    cmds:
      - uv run pytest --cov=lofigui --cov-report=html --cov-report=xml --cov-report=term-missing

  lint:
    desc: Run all linters
    cmds:
      - task: lint-black
      - task: lint-flake8
      # - task: lint-mypy

  lint-black:
    desc: Check code formatting with black
    cmds:
      - .venv/bin/black --check lofigui tests

  lint-flake8:
    desc: Run flake8 linter
    cmds:
      - .venv/bin/flake8 lofigui tests --max-line-length=100 --extend-ignore=E203,W503,F401

  lint-mypy:
    desc: Run mypy type checker
    cmds:
      - .venv/bin/mypy lofigui

  format:
    desc: Format code with black
    cmds:
      - .venv/bin/black lofigui tests

  fmt:
    desc: Format all code (Go + Python)
    cmds:
      - gofmt -w .
      - task: format

  vet:
    desc: Run Go vet
    cmds:
      - go vet ./...

  check:
    desc: Run fmt, vet, and test
    cmds:
      - task: fmt
      - task: vet
      - task: test

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf dist/ *.egg-info __pycache__ .pytest_cache .mypy_cache .coverage htmlcov
      - find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
      - rm -f examples/03_hello_world_wasm/go/main.wasm 2>/dev/null || true
      - rm -f examples/04_tinygo_wasm/go/main.wasm 2>/dev/null || true

  check-licenses:
    desc: Check Go dependencies for license compliance
    cmds:
      - go install github.com/google/go-licenses@latest
      - go-licenses check ./... --allowed_licenses MIT,Apache-2.0,BSD-2-Clause,BSD-3-Clause,ISC,MPL-2.0

  build:
    desc: Build package distribution
    cmds:
      - uv build

  # Python example tasks
  example-01:
    desc: Run Python example 01 (Hello World with FastAPI)
    aliases: [py01]
    dir: examples/01_hello_world/python
    cmds:
      - uv sync --no-install-project
      - uv run --no-project python hello.py

  example-02:
    desc: Run Python example 02 (SVG Graph with Pygal)
    aliases: [py02]
    dir: examples/02_svg_graph/python
    cmds:
      - uv sync --no-install-project
      - uv run --no-project python graph.py

  example-05:
    desc: Run Python example 05 (Demo App with template inheritance)
    aliases: [py05, demo]
    dir: examples/05_demo_app
    cmds:
      - uv sync --no-install-project
      - uv run --no-project python demo_app.py

  example-06:
    desc: Run Python example 06 (Notes CRUD)
    aliases: [py06]
    dir: examples/06_notes_crud/python
    cmds:
      - uv sync --no-install-project
      - uv run --no-project python notes.py

  # Go example tasks (wildcard)
  go-example:*:
    desc: 'Run Go example (use go-wasm:NN for WASM examples)'
    vars:
      NUM: '{{index .MATCH 0}}'
      EXAMPLE_DIR:
        sh: ls -d examples/{{index .MATCH 0}}_*/go 2>/dev/null || echo ""
    preconditions:
      - sh: '[ -n "{{.EXAMPLE_DIR}}" ]'
        msg: 'No Go example found for number {{.NUM}}'
      - sh: '[ ! -f "build.sh" ]'
        msg: 'Example {{.NUM}} is a WASM example — use task go-wasm:{{.NUM}} instead'
    dir: '{{.EXAMPLE_DIR}}'
    cmds:
      - go mod tidy
      - go run .

  go-wasm:*:
    desc: 'Build and serve Go WASM example'
    vars:
      NUM: '{{index .MATCH 0}}'
      EXAMPLE_DIR:
        sh: ls -d examples/{{index .MATCH 0}}_*/go 2>/dev/null || echo ""
    preconditions:
      - sh: '[ -n "{{.EXAMPLE_DIR}}" ]'
        msg: 'No Go example found for number {{.NUM}}'
      - sh: '[ -f "build.sh" ]'
        msg: 'Example {{.NUM}} is not a WASM example — use task go-example:{{.NUM}} instead'
    dir: '{{.EXAMPLE_DIR}}'
    cmds:
      - chmod +x build.sh
      - ./build.sh
      - echo ""
      - echo "Build complete! Starting server..."
      - cd .. && {{.PYTHON}} serve.py

  build-wasm:*:
    desc: 'Build WASM binary only (no serve)'
    vars:
      NUM: '{{index .MATCH 0}}'
      EXAMPLE_DIR:
        sh: ls -d examples/{{index .MATCH 0}}_*/go 2>/dev/null || echo ""
    preconditions:
      - sh: '[ -n "{{.EXAMPLE_DIR}}" ]'
        msg: 'No Go example found for number {{.NUM}}'
      - sh: '[ -f "build.sh" ]'
        msg: 'Example {{.NUM}} is not a WASM example'
    dir: '{{.EXAMPLE_DIR}}'
    cmds:
      - chmod +x build.sh
      - ./build.sh

  build-pages:
    desc: Build WASM examples for GitHub Pages docs/ folder
    vars:
      WASM_EXEC_JS:
        sh: find $(go env GOROOT) -name wasm_exec.js -print -quit
    cmds:
      # 01 Hello World
      - mkdir -p docs/01_hello_world
      - cd examples/01_hello_world/go && GOOS=js GOARCH=wasm go build -o main.wasm .
      - cp "{{.WASM_EXEC_JS}}" docs/01_hello_world/
      - cp examples/01_hello_world/go/main.wasm docs/01_hello_world/
      - cp examples/01_hello_world/templates/index.html docs/01_hello_world/
      - cp examples/01_hello_world/templates/app.js docs/01_hello_world/
      - rm examples/01_hello_world/go/main.wasm
      # 03 Hello World WASM
      - mkdir -p docs/03_hello_world_wasm
      - cd examples/03_hello_world_wasm/go && GOOS=js GOARCH=wasm go build -o main.wasm .
      - cp "{{.WASM_EXEC_JS}}" docs/03_hello_world_wasm/
      - cp examples/03_hello_world_wasm/go/main.wasm docs/03_hello_world_wasm/
      - cp examples/03_hello_world_wasm/templates/index.html docs/03_hello_world_wasm/
      - cp examples/03_hello_world_wasm/templates/app.js docs/03_hello_world_wasm/
      - rm examples/03_hello_world_wasm/go/main.wasm
      # 07 Water Tank
      - mkdir -p docs/07_water_tank
      - cd examples/07_water_tank/go && GOOS=js GOARCH=wasm go build -o main.wasm .
      - cp "{{.WASM_EXEC_JS}}" docs/07_water_tank/
      - cp examples/07_water_tank/go/main.wasm docs/07_water_tank/
      - cp examples/07_water_tank/templates/index.html docs/07_water_tank/
      - cp examples/07_water_tank/templates/app.js docs/07_water_tank/
      - rm examples/07_water_tank/go/main.wasm
      # 08 Water Tank Multi-Page
      - mkdir -p docs/08_water_tank_multi
      - cd examples/08_water_tank_multi/go && GOOS=js GOARCH=wasm go build -o main.wasm .
      - cp "{{.WASM_EXEC_JS}}" docs/08_water_tank_multi/
      - cp examples/08_water_tank_multi/go/main.wasm docs/08_water_tank_multi/
      - cp examples/08_water_tank_multi/templates/index.html docs/08_water_tank_multi/
      - cp examples/08_water_tank_multi/templates/app.js docs/08_water_tank_multi/
      - rm examples/08_water_tank_multi/go/main.wasm

  # Go module tidy tasks (wildcard)
  tidy:
    desc: Run go tidy and update for all
    deps: [tidy:main, tidy:01, tidy:02, tidy:03, tidy:04, tidy:06, tidy:07, tidy:08, tidy:09]

  tidy:main:
    desc: Run go tidy and update main
    cmds:
      - go mod tidy
      - go get -u ./...

  tidy:*:
    desc: 'Run go tidy and update for example'
    vars:
      NUM: '{{index .MATCH 0}}'
      EXAMPLE_DIR:
        sh: ls -d examples/{{index .MATCH 0}}_*/go 2>/dev/null || echo ""
    preconditions:
      - sh: '[ -n "{{.EXAMPLE_DIR}}" ]'
        msg: 'No Go example found for number {{.NUM}}'
    dir: '{{.EXAMPLE_DIR}}'
    cmds:
      - go mod tidy
      - go get -u ./...

  # # Release task
  # release:
  #   desc: 'Release process eg task release VERSION=v0.14.0 COMMENT="new feature"'
  #   requires:
  #     vars: [VERSION, COMMENT]
  #   cmds:
  #     - task: test
  #     - task: lint
  #     - task: build
  #     - git add .
  #     - git commit -am "{{.COMMENT}}"
  #     - git tag "{{.VERSION}}"
  #     - git push origin "{{.VERSION}}"
  #     - git push
