# https://taskfile.dev

version: '3'

vars:
  PYTHON: python3

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  # Development tasks
  install:
    desc: Install development dependencies
    cmds:
      - uv sync --all-extras

  test:
    desc: Run tests
    cmds:
      - uv run pytest

  test-coverage:
    desc: Run tests with coverage report
    cmds:
      - uv run pytest --cov=lofigui --cov-report=html --cov-report=term-missing

  lint:
    desc: Run all linters
    cmds:
      - task: lint-black
      - task: lint-flake8
      - task: lint-mypy

  lint-black:
    desc: Check code formatting with black
    cmds:
      - uv run black --check lofigui tests

  lint-flake8:
    desc: Run flake8 linter
    cmds:
      - uv run flake8 lofigui tests --max-line-length=100 --extend-ignore=E203,W503

  lint-mypy:
    desc: Run mypy type checker
    cmds:
      - uv run mypy lofigui

  format:
    desc: Format code with black
    cmds:
      - uv run black lofigui tests

  build:
    desc: Build package distribution
    cmds:
      - uv build

  # Example tasks
  example-01:
    desc: Run example 01 (Hello World with FastAPI)
    dir: examples/01_hello_world
    cmds:
      - uv sync --no-install-project
      - uv run --no-project python hello.py

  example-02:
    desc: Run example 02 (SVG Graph with Pygal)
    dir: examples/02_svg_graph
    cmds:
      - uv sync --no-install-project
      - uv run --no-project python graph.py

  # Go example tasks
  go-example-01:
    desc: Run Go example 01 (Hello World with net/http)
    dir: go/examples/01_hello_world
    cmds:
      - go mod download
      - go run main.go

  go-example-02:
    desc: Run Go example 02 (SVG Graph)
    dir: go/examples/02_svg_graph
    cmds:
      - go mod download
      - go run main.go

  go-example-03:
    desc: Build and serve Go WASM example
    aliases: [go-wasm]
    dir: go/examples/03_hello_world_wasm
    cmds:
      - chmod +x build.sh
      - ./build.sh
      - echo ""
      - echo "Build complete! Starting server..."
      - "{{.PYTHON}} serve.py"

  build-go-wasm:
    desc: Build Go WASM binary only (no serve)
    dir: go/examples/03_hello_world_wasm
    cmds:
      - chmod +x build.sh
      - ./build.sh

