# https://taskfile.dev

version: "3"

vars:
  PYTHON: python3

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  # Development tasks
  install:
    desc: Install development dependencies
    cmds:
      - uv sync --all-extrass

  test:
    desc: Run tests
    cmds:
      - uv run pytest
      - go test ./...

  test-coverage:
    desc: Run tests with coverage report
    cmds:
      - uv run pytest --cov=lofigui --cov-report=html --cov-report=term-missing

  lint:
    desc: Run all linters
    cmds:
      - task: lint-black
      - task: lint-flake8
      - task: lint-mypy

  lint-black:
    desc: Check code formatting with black
    cmds:
      - uv run black --check lofigui tests

  lint-flake8:
    desc: Run flake8 linter
    cmds:
      - uv run flake8 lofigui tests --max-line-length=100 --extend-ignore=E203,W503

  lint-mypy:
    desc: Run mypy type checker
    cmds:
      - uv run mypy lofigui

  format:
    desc: Format code with black
    cmds:
      - uv run black lofigui tests

  build:
    desc: Build package distribution
    cmds:
      - uv build

  # Python example tasks
  example-01:
    desc: Run Python example 01 (Hello World with FastAPI)
    aliases: [py01]
    dir: examples/01_hello_world/python
    cmds:
      - uv sync --no-install-project
      - uv run --no-project python hello.py

  example-02:
    desc: Run Python example 02 (SVG Graph with Pygal)
    aliases: [py02]
    dir: examples/02_svg_graph/python
    cmds:
      - uv sync --no-install-project
      - uv run --no-project python graph.py

  # Go example tasks
  go-example-01:
    desc: Run Go example 01 (Hello World with net/http)
    aliases: [go01]
    dir: examples/01_hello_world/go
    cmds:
      - go mod download
      - go run main.go

  go-example-02:
    desc: Run Go example 02 (SVG Graph)
    aliases: [go02]
    dir: examples/02_svg_graph/go
    cmds:
      - go mod download
      - go run main.go

  go-example-03:
    desc: Build and serve Go WASM example
    aliases: [go03, go-wasm]
    dir: examples/03_hello_world_wasm/go
    cmds:
      - chmod +x build.sh
      - ./build.sh
      - echo ""
      - echo "Build complete! Starting server..."
      - cd .. && "{{.PYTHON}} serve.py"

  build-go-wasm:
    desc: Build Go WASM binary only (no serve)
    dir: examples/03_hello_world_wasm/go
    cmds:
      - chmod +x build.sh
      - ./build.sh
